/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7299c601-41fb-4c8b-a2cd-6359f47217eb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4U2Qkx9am",
    "aws_user_pools_web_client_id": "3m08m221rak6qlbdan3ae65k1a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7ae2fp35zjdpbdrdq4fryz2mtq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
